### PR TITLE
Build a cash register App

### PR DESCRIPTION
**Pull request by MasomRezaie**
This is a cash register app that will return change to the customer based on the price of the item, the amount of cash provided by the customer, and the amount of cash in the cash drawer. You'll also need to show different messages to the user in different scenarios, such as when the customer provides too little cash or when the cash drawer doesn't have enough to issue the correct change.
Demo

### CODE REVIEW

**Comment by MasomRezaie** [comment]
@ahzamir
Hi sir, this my project has linters error that i talked about it in the class. Kindly request you once review that what is the solution.

**Comment by ahzamir** [comment]
> @ahzamir Hi sir, this my project has linters error that i talked about it in the class. Kindly request you once review that what is the solution.

- @MasomRezaie 

  - As the error says, you must move your function above before you call them.

**Comment by FarwaMuhibZada** [comment]
dear @MasomRezaie !
status: APPROVED
you did a great job 
Linter  set up correctly for this repository.
Linter result are  green.
There are no custom changes to linter config.
 you used correct GitHub Flow
README file is descriptive.
Commit messages are  meaningful.
Pull Request  have a descriptive title explaining what changes are inside.
your project pass freecode camp requirements

**Comment by MasomRezaie** [comment]
@ahzamir my project is ready to review.

**Review by ahzamir — APPROVED** [review]
### Hi @MasomRezaie 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
image

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

WinkThumbsUpGIF

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Cash Register project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️ Your partner has reviewed your repo
✔️Your design is responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me @ahzamir in your question so I can receive the notification.**

**Pull request merged**
